[package]
name = "httpinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow      = "1.0"          # ergonomic error handling
reqwest     = { version = "0.11", features = ["blocking", "json"] }
serde_json  = "1.0"          # pretty JSON formatting
